# gateway
# Run
#   ansible-playbook --vault-pass-file=~/my-vault-pass --extra-vars=@~/vault-credentials.yml \
#      playbooks/gateway_vm.yml
# These plays are copied from here.
#   https://github.com/nickhardiman/ansible-collection-vm-gateway/tree/main/playbooks
# * build_vm.yml
# * configure_os.yml
# * update_etc_hosts.yml


- name: Install RPMs n stuff
  ansible.builtin.import_playbook: playbooks/hypervisor_os.yml
- name: Install libvirt n stuff
  ansible.builtin.import_playbook: playbooks/hypervisor_libvirt.yml
- name: Gateway VM from the private network to the world
  ansible.builtin.import_playbook: playbooks/gateway_vm.yml
- name: Gateway OS
  ansible.builtin.import_playbook: playbooks/gateway_os.yml
- name: Gateway names and addresses to /etc/hosts
  ansible.builtin.import_playbook: playbooks/gateway_hosts.yml
- name: Satellite VM on private network
  ansible.builtin.import_playbook: playbooks/satellite_vm.yml
- name: Satellite OS
  ansible.builtin.import_playbook: playbooks/satellite_os.yml
- name: Satellite repo and RPM
  ansible.builtin.import_playbook: playbooks/satellite_app_install.yml
- name: Satellite config-as-code
  ansible.builtin.import_playbook: playbooks/satellite_app_configure.yml
